modLoader = 'lowcodefml'
showAsResourcePack = false
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="super_reality"
displayName="Super Reality"
version="1.0"
logoFile = "logo.png"
logoBlur = false
description='''
Shattered Reality Palladium resources
'''

[[dependencies.super_reality]]
modId = "palladium"
mandatory = true
versionRange = ""
ordering = "NONE"
side = "BOTH"
